### ISSUE TITLE
Android TODO

### ISSUE THREAD

**Issue by olegwn** [dater-com/dater-react-native#91]
Auth Phone:

- [ ] non implemented AUTO_VERIFY_TIMEOUT
- [ ] non implemented AUTO_VERIFIED

- [ ] Non implemented FMC Push for Android in firebase

- [ ] Firebase not working
